name: Build and Publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  image-name: ghcr.io/mushi123/weatherforecast:${{ github.sha }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v2
      
      - name: Build docker image
        run: docker build --platform linux/arm64 . -t ${{ env.image-name }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_CR }}
      - name: Push docker image
        run: docker push ${{ env.image-name }}
