name: Build and Publish
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  image-name: ghcr.io/mushi123/weatherforecast:${{ github.sha }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      
      - name: Build docker image
        run: docker build --platform linux/arm64 -t ${{ env.image-name }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_CR }}
      - name: Push docker image
        run: docker push ${{env.image-name}}
          # docker buildx build --platform linux/arm64 --tag ${{ env.image-name }} --output "type=image,push=true" --file . .
